server:
  port: 9999

spring:
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

security:
  config:
    enable: true #是否开启spring security 如果关闭 则不可使用@PreAuthorize注解
    ignore-interface: [ /test/login ] #Security 不拦截接口
    logout-path: /test/exit #定义退出接口路径 若定义该路径则不会走自己定义的controller方法,可以实现LogoutSuccessHandler接口进行重写
jwt:
  config:
    prefix: Bearer #JWT前缀
    header: Authorization #JWT token 请求头
    expiration: 60 #默认过期时间
    expiration-remember: 604800 #勾选记住我的过期时间
    secret: 441E0738EC706461B33D9FC3CF86B2ADFA27FDD6DD90A7426660D1304804DD5C #JWT密钥(SHA256)
